language: haskell
before_install:
  - sudo add-apt-repository --yes ppa:h-rayflood/llvm
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgc-dev llvm-3.3
install:
  - cabal install -f FFI -f LLVM --only-dependencies --enable-tests
before_script:
  - cabal sdist
  - cd ..
  - tar -xf Idris-dev/dist/idris*.tar.gz
  - cd idris*
script:
  - cabal configure -f FFI -f LLVM
  - cabal build
  - cabal copy
  - make -j2 test
  - make -j2 test_llvm
  - make -j2 test_java

