language: haskell
before_install:
  - sudo sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise main' >> /etc/apt/sources.list"
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgc-dev llvm-3.3
before_script:
  - cabal sdist
  - cd ../..
  - tar -xf edwinb/Idris-dev/dist/idris*.tar.gz
  - cd idris*
  - sed -i -e "s/#CABALFLAGS\(\s\+\):=-f Java/CABALFAGS\1:=-f Java/g" config.mk 
script:
  - cabal configure
  - cabal install
  - make test
  - make test_java

